[build]
  command = "npm run build"
  publish = "build"
  environment = { NODE_VERSION = "20" }




[build]
  command = "npm run build"
  publish = "client/build"
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/json-server/:splat"
  status = 200
