[build]
  command = "NODE_OPTIONS=--openssl-legacy-provider npm run build"
  publish = "build"

[context.production.environment]
  NODE_VERSION = "20"
  NODE_OPTIONS = "--openssl-legacy-provider"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/json-server/:splat"
  status = 200
