[build]
  command = "npm run build"
  publish = "client/build"

[context.production.environment]
  NODE_VERSION = "20"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/json-server/:splat"
  status = 200
